### ISSUE TITLE
mvn clean package打包后报错

### ISSUE THREAD

**Issue by KlinKlinKlin** [Moon3r/AKtools#1]
Exception in thread "main" java.lang.NullPointerException
	at com.kkzevip.AKTools.<init>(AKTools.java:46)
	at com.kkzevip.AKTools.main(AKTools.java:233)

**Comment by Moon3r** [comment]
用Idea的Lifecycle打包没问题，可能是ui部分没有自己去绑定生成，用mvn打包会出问题。
